default:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

stages:
  - test
  - build
  - deploy

#format:
#  stage: test
#  script:
#    - pnpm run format
#
#lint:
#  stage: test
#  script:
#    - pnpm run lint

vite:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    VITE_BUILD_VERSION: $CI_COMMIT_TAG
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/
    expire_in: 30 days
#
# The GitLab instance of the University of Lille does not have a Docker
# container registry (yet!). For now, we are using a private Docker Hub
# repository instead. Hopefully, we will be able to migrate very soon!
#
dockerize:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  script:
    - ls -la
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  dependencies:
    - vite
