stages:
  - validate
  - build
  - docker

default:
  image: node:20-slim
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

format:
  stage: validate
  rules:
    - if: $CI_COMMIT_TAG
    - when: on_success
      interruptible: true
  script:
    - pnpm run prettier

lint:
  stage: validate
  rules:
    - if: $CI_COMMIT_TAG
    - when: on_success
      interruptible: true
  script:
    - pnpm run eslint

vite-build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        VITE_BUILD_VERSION: $CI_COMMIT_TAG
    - when: on_success
      interruptible: true
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/

docker-build:
  stage: docker
  rules:
    - if: $CI_COMMIT_TAG
    - when: on_success
      interruptible: true
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375/"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - IMAGE_ID="$(docker build . --quiet)"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$IMAGE_ID" "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" 
        docker tag "$IMAGE_ID" "$CI_REGISTRY_IMAGE:latest"
      else
        docker tag "$IMAGE_ID" "$CI_REGISTRY_IMAGE:edge"
      fi
      docker push --all-tags "$CI_REGISTRY_IMAGE"
  dependencies:
    - vite-build
